"use strict"
function footerUI(){
	return '<footer>'
	+'  <div class="footer_container">'
	+'    <div class="company_info_container">'
	+'      <h2 class="name">(주)야놀자</h2>'
	+'      <span>서울특별시 강남구 테헤란로 108길 42 (대치동 1003)</span>'
	+'      <div style="flex-direction: row">'
	+'        <a href="tel:1644-1346">Tel. 1644-1346</a>'
	+'        <div style="flex:1"></div>'
	+'      </div>'
	+'      <span>Fax. 02-548-1886</span>'
	+'      <div style="flex-direction: row">'
	+'        <a href="mailto:contact@yanolja.com">contact@yanolja.com</a>'
	+'        <div style="flex:1"></div>'
	+'      </div>'
	+'      <span class="copyright">Copyright © 2005-2018 Yanolja Co., Ltd. All rights reserved.</span>'
	+'    </div>'
	+'    <div class="misc_container">'
	+'      <div class="btn_container">'
	+'        <a href="http://yanolja.in/wp-content/uploads/2018/06/yanolja_introduction_201806.pdf" target="_blank" class="btn_download">회사 소개서</a>'
	+'        <dl class="btn_familysite">'
	+'          <dt>패밀리사이트</dt>'
	+'          <dd style="display: none;">'
	+'            <ul>'
	+'              <a href="http://www.yanolja.com/" target="_blank"><li>야놀자</li></a>'
	+'              <a href="http://www.yapen.co.kr/" target="_blank"><li>야놀자펜션</li></a>'
	+'              <a href="http://www.hotelnow.co.kr/" target="_blank"><li>호텔나우</li></a>'
	+'              <a href="http://www.hotelup.com/" target="_blank"><li>호텔업</li></a>'
	+'              <a href="http://ynjedu.co.kr/" target="_blank"><li>야놀자 평생교육원</li></a>'
	+'              <a href="http://bipumstore.com/" target="_blank"><li>비품스토어</li></a>'
	+'            </ul>'
	+'          </dd>'
	+'        </dl>'
	+'      </div>'
	+'    </div>'
	+'  </div>'
	+'</footer>';
}